
on:
  pull_request:
    types:
      - opened
      - synchronize
    
jobs:
  codege:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: setup aws cli
        run: |
          aws configure set aws_access_key_id ${{secrets.AMPLIFY_CICD_ACCESS_KEY}}  --profile default
          aws configure set aws_secret_access_key ${{secrets.AMPLIFY_CICD_SECRET_KEY}}  --profile default
          aws configure set default.region ap-northeast-1
          npm install -g @aws-amplify/cli --unsafe-perm=true
          bash init.sh
          bash push.sh
          amplify codegen